import avatarImg from "../../assets/avatar-1.png";

export const data = [
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 10,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 20,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
  {
    avatar: avatarImg,
    email: "anderson.cooper@example.com",
    status: Math.random() >= 0.5 ? "active" : "registered",
    reward: 30,
  },
];
